### ISSUE TITLE
Disabled ModalClose after unsuccessful matching

### ISSUE THREAD

**Issue by panpannnnn** [CS3219-AY2324S1/ay2324s1-course-assessment-g43#42]
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g43/assets/85011179/3d337b44-2f13-4909-9401-f5cb2f21cf0f)

**Comment by changjy44** [comment]
Resolved with commit [cea08e2](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g43/commit/cea08e238c71a65a2728970e09b64cb749040fbd)
